export interface StationaryCatalogItem {
  name: string;
  category: string;
  unit: string;
}

export const STATIONARY_CATALOG: StationaryCatalogItem[] = [
  { name: "APSARA PLATINUM PENCILS (1 Box = 10 Nos)", category: "Pencils & Sharpeners", unit: "Box" },
  { name: "CAMEL PENCIL WITH ERASER", category: "Pencils & Sharpeners", unit: "Nos" },
  { name: "APSARA NON-DUST ERASER", category: "Pencils & Sharpeners", unit: "Nos" },
  { name: "NATRAJ SHARPENER", category: "Pencils & Sharpeners", unit: "Nos" },
  { name: "NATRAJ ERASER", category: "Pencils & Sharpeners", unit: "Nos" },
  { name: "SAINO STAR FLOW BALL PENS", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "SAINO SOFT TEC TRIO BALL PENS – BLUE", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "SPEED BLUE PENS", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "SPEED BLACK PENS", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "SPEED RED PENS", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "NATRAJ PENS JOR", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "ADD GEL PENS – GREEN", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "ADD GEL REFILLS – GREEN GR-20", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "ADD GEL PENS – BLUE", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "ADD GEL PENS – BLACK", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "ADD GEL PENS – RED", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "ADD GEL PIN-GEL – GREEN", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "ADD GEL PIN-GEL – RED", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "LINC OCEAN GEL PENS – BLUE (1 Packet = 3 Nos)", category: "Pens & Gel Pens", unit: "Packet" },
  { name: "LINC OCEAN GEL PENS – BLACK (1 Packet = 3 Nos)", category: "Pens & Gel Pens", unit: "Packet" },
  { name: "LINC OCEAN GEL PENS – RED (1 Packet = 3 Nos)", category: "Pens & Gel Pens", unit: "Packet" },
  { name: "LINC OCEAN GEL PENS – GREEN (1 Packet = 3 Nos)", category: "Pens & Gel Pens", unit: "Packet" },
  { name: "UNI BALL PENS – GREEN", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "UNI BALL PENS – BLACK", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "CAMEL OHP/CD MARKER – BLUE (1 Box = 10 Nos)", category: "Markers & Highlighters", unit: "Box" },
  { name: "CAMEL OHP/CD MARKER – BLACK (1 Box = 10 Nos)", category: "Markers & Highlighters", unit: "Box" },
  { name: "CAMEL OHP/CD MARKER – RED (1 Box = 10 Nos)", category: "Markers & Highlighters", unit: "Box" },
  { name: "CAMEL OHP/CD MARKER – GREEN (1 Box = 10 Nos)", category: "Markers & Highlighters", unit: "Box" },
  { name: "CAMEL PERMANENT MARKER – RED", category: "Markers & Highlighters", unit: "Nos" },
  { name: "CAMEL PERMANENT MARKER – BLUE", category: "Markers & Highlighters", unit: "Nos" },
  { name: "CAMEL PERMANENT MARKER – BLACK", category: "Markers & Highlighters", unit: "Nos" },
  { name: "CAMEL WHITE BOARD MARKER PENS – BLUE", category: "Markers & Highlighters", unit: "Nos" },
  { name: "CAMEL WHITE BOARD MARKER PENS – BLACK", category: "Markers & Highlighters", unit: "Nos" },
  { name: "CAMEL WHITE BOARD MARKER PENS – RED", category: "Markers & Highlighters", unit: "Nos" },
  { name: "CAMEL WHITE BOARD MARKER INK – BLUE", category: "Inks & Stamp Pads", unit: "Bottle" },
  { name: "CAMEL WHITE BOARD MARKER INK – BLACK", category: "Inks & Stamp Pads", unit: "Bottle" },
  { name: "CAMEL WHITE BOARD MARKER INK – RED", category: "Inks & Stamp Pads", unit: "Bottle" },
  { name: "FABER-CASTELL HIGHLIGHTER – YELLOW", category: "Markers & Highlighters", unit: "Nos" },
  { name: "CAMEL ERAZEX PEN – WHITE FLUID", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "SD MINI CUTTER – STEEL BLADES", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "SKETCH PENS – BLUE", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "SKETCH PENS – BLACK", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "SKETCH PENS – RED", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "SKETCH PENS – GREEN", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "SKETCH PENS – PINK", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "SKETCH PENS – ALL COLOURS", category: "Pens & Gel Pens", unit: "Set" },
  { name: "KORES WHITE CHALK PIECES – DUSTLESS (1 Box = 18 Nos)", category: "Chalks & Media", unit: "Box" },
  { name: "KORES COLOUR CHALK PIECES – DUSTLESS (1 Box = 18 Nos)", category: "Chalks & Media", unit: "Box" },
  { name: "SONY CD", category: "Chalks & Media", unit: "Nos" },
  { name: "SONY DVD", category: "Chalks & Media", unit: "Nos" },
  { name: "CD MAILER – HANDLE WITH CARE", category: "Chalks & Media", unit: "Nos" },
  { name: "CD COVERS", category: "Chalks & Media", unit: "Nos" },
  { name: "CD POUCHES – BAG", category: "Chalks & Media", unit: "Nos" },
  { name: "ASHOK SEALING WAX (1 Box = 10 Nos)", category: "General & Miscellaneous", unit: "Box" },
  { name: "NAYAGARA BOX FILES – BIG", category: "Files & Folders", unit: "Nos" },
  { name: "NAYAGARA BOX FILES – BIG STEEL CLIPS (GOOD QUALITY)", category: "Files & Folders", unit: "Nos" },
  { name: "NAYAGARA BOX FILES – SMALL 1/4", category: "Files & Folders", unit: "Nos" },
  { name: "NAYAGARA URGENT & ORDINARY PADS (1 Packet = 12 Nos)", category: "Pads & Notebooks", unit: "Packet" },
  { name: "NAYAGARA PVC FOLDERS – LEGAL", category: "Files & Folders", unit: "Nos" },
  { name: "NAYAGARA PVC FOLDERS – A4", category: "Files & Folders", unit: "Nos" },
  { name: "NAYAGARA PVC FOLDERS – A3", category: "Files & Folders", unit: "Nos" },
  { name: "SUN 150 FOLDERS – LEGAL", category: "Files & Folders", unit: "Nos" },
  { name: "SUN 150 FOLDERS – LEGAL (WITHOUT FILING)", category: "Files & Folders", unit: "Nos" },
  { name: "SUN 150 FOLDERS – A4", category: "Files & Folders", unit: "Nos" },
  { name: "SUN 200 FOLDERS – A4", category: "Files & Folders", unit: "Nos" },
  { name: "TAPE DISPENSER – TAPE CUTTER", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "BROWN ENVELOPE COVERS – 6 X 4", category: "Envelopes & Covers", unit: "Nos" },
  { name: "BROWN ENVELOPE COVERS – 10 X 4", category: "Envelopes & Covers", unit: "Nos" },
  { name: "BROWN ENVELOPE COVERS – 11 X 5", category: "Envelopes & Covers", unit: "Nos" },
  { name: "BROWN COVERS – A4", category: "Envelopes & Covers", unit: "Nos" },
  { name: "WHITE ENVELOPE COVERS – 6 X 4", category: "Envelopes & Covers", unit: "Nos" },
  { name: "WHITE ENVELOPE COVERS – 10 X 4", category: "Envelopes & Covers", unit: "Nos" },
  { name: "WHITE ENVELOPE COVERS – 11 X 5", category: "Envelopes & Covers", unit: "Nos" },
  { name: "BROWN ENVELOPE COVERS – 11 X 5 (THICK)", category: "Envelopes & Covers", unit: "Nos" },
  { name: "CLOTH COVERS – 11 X 5", category: "Envelopes & Covers", unit: "Nos" },
  { name: "CLOTH COVERS – 12 X 10 (1 Packet = 100 Nos)", category: "Envelopes & Covers", unit: "Packet" },
  { name: "CLOTH COVERS – 15 X 11 (1 Packet = 100 Nos)", category: "Envelopes & Covers", unit: "Packet" },
  { name: "CLOTH COVERS – 16 X 12 (1 Packet = 100 Nos)", category: "Envelopes & Covers", unit: "Packet" },
  { name: "CLOTH COVERS – A4 (1 Packet = 100 Nos)", category: "Envelopes & Covers", unit: "Packet" },
  { name: "KANGARO STAPLER – MISSION No.10 ICON (1 Box = 10 Nos)", category: "Staplers & Punches", unit: "Box" },
  { name: "KANGARO STAPLER – MISSION 10-D (1 Box = 10 Nos)", category: "Staplers & Punches", unit: "Box" },
  { name: "KANGARO STAPLER – MISSION HP-45 (BIG)", category: "Staplers & Punches", unit: "Nos" },
  { name: "KANGARO STAPLES PIN No.10-1M (1 Box = 20 Packets)", category: "Staplers & Punches", unit: "Box" },
  { name: "KANGARO STAPLES PIN – BIG 24/6", category: "Staplers & Punches", unit: "Box" },
  { name: "KANGARO PUNCHING MISSION SMALL 280 – 8 CM", category: "Staplers & Punches", unit: "Nos" },
  { name: "KANGARO PUNCHING MISSION DP-500", category: "Staplers & Punches", unit: "Nos" },
  { name: "KANGARO PUNCHING MISSION DP-700", category: "Staplers & Punches", unit: "Nos" },
  { name: "KANGARO SINGLE PUNCH – 2 MM PUNCHING CAPACITY", category: "Staplers & Punches", unit: "Nos" },
  { name: "PAPER WEIGHT – RUBBER GENERAL", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "NATRAJ SCALE LONG – 30 CMS (GENERAL)", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "STEEL SCALES – LONG", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "IRON CLIPS – TIGER", category: "Clips, Pins & Tags", unit: "Nos" },
  { name: "KENT LAMINATION POUCH – 75 X 105 MM, 250 MIC", category: "General & Miscellaneous", unit: "Packet" },
  { name: "FEVI STICK – 8 GMS (1 Box = 30 Nos)", category: "Adhesives & Tapes", unit: "Box" },
  { name: "FEVI KWIK – 1 GM", category: "Adhesives & Tapes", unit: "Nos" },
  { name: "CALCULATOR – CITIZEN 512 GENERAL", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "CALCULATOR – CITICAL CT-512 GST", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "CAMEL STAMP PAD MEDIUM No.2 – 110 X 70 MM, VIOLET (1 Box = 10 Nos)", category: "Inks & Stamp Pads", unit: "Box" },
  { name: "CAMEL STAMP PAD MEDIUM – 45, VIOLET", category: "Inks & Stamp Pads", unit: "Nos" },
  { name: "CAMEL STAMP PAD MEDIUM No.2 – 110 X 70 MM, GREEN (1 Box = 10 Nos)", category: "Inks & Stamp Pads", unit: "Box" },
  { name: "CAMEL STAMP PAD LARGE – 70, RED", category: "Inks & Stamp Pads", unit: "Nos" },
  { name: "CAMEL STAMP PAD LARGE – 70, VIOLET", category: "Inks & Stamp Pads", unit: "Nos" },
  { name: "CAMEL STAMP PAD LARGE UN (PLAIN) – 70", category: "Inks & Stamp Pads", unit: "Nos" },
  { name: "A4 TRANSPARENCY FILM (OHP SHEETS)", category: "Chalks & Media", unit: "Packet" },
  { name: "A4 COLOUR OHP SHEETS", category: "Chalks & Media", unit: "Packet" },
  { name: "BRILL STAMP PAD INK – 700 ML, VIOLET", category: "Inks & Stamp Pads", unit: "Bottle" },
  { name: "BRILL STAMP PAD INK – 350 ML, VIOLET", category: "Inks & Stamp Pads", unit: "Bottle" },
  { name: "BRILL STAMP PAD INK – 350 ML, RED", category: "Inks & Stamp Pads", unit: "Bottle" },
  { name: "BRILL STAMP PAD INK – 100 ML, GREEN", category: "Inks & Stamp Pads", unit: "Bottle" },
  { name: "NAPTHALENE BALLS – 500 G PACKET", category: "General & Miscellaneous", unit: "Packet" },
  { name: "PENCIL CELL – 9V", category: "General & Miscellaneous", unit: "Nos" },
  { name: "DURACELL AA – GENERAL SIZE (1 Sheet = 10 Nos)", category: "General & Miscellaneous", unit: "Sheet" },
  { name: "DURACELL AAA – SMALL SIZE (1 Sheet = 10 Nos)", category: "General & Miscellaneous", unit: "Sheet" },
  { name: "NIPPO PENCIL CELLS – AA GENERAL SIZE", category: "General & Miscellaneous", unit: "Nos" },
  { name: "NIPPO PENCIL CELLS – AAA SMALL SIZE", category: "General & Miscellaneous", unit: "Nos" },
  { name: "LOCK – 50 MM (Rs.50/-)", category: "General & Miscellaneous", unit: "Nos" },
  { name: "SCISSOR – SMALL WILSON – 11.55 MM (ORDINARY)", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "SCISSOR – MEDIUM EAGLE-666 – 16.5 MM (ORDINARY)", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "SCISSOR – BIG EAGLE-777 – 17.5 MM (ORDINARY)", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "DUSTER – AGRA", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "WHITE BOARD DUSTER", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "PREMIER CELLO TAPE – 1\"", category: "Adhesives & Tapes", unit: "Roll" },
  { name: "CELLO TAPE BROWN – 1.5\", 60 MTR TUBE", category: "Adhesives & Tapes", unit: "Roll" },
  { name: "CELLO TAPE BROWN – 2\", 60 MTR TUBE", category: "Adhesives & Tapes", unit: "Roll" },
  { name: "CELLO TAPE BROWN – 3\", 60 MTR TUBE", category: "Adhesives & Tapes", unit: "Roll" },
  { name: "CELLO TAPE WHITE – 1\", 60 MTR TUBE", category: "Adhesives & Tapes", unit: "Roll" },
  { name: "CELLO TAPE WHITE – 1.5\", 60 MTR TUBE", category: "Adhesives & Tapes", unit: "Roll" },
  { name: "CELLO TAPE WHITE – 2\", 60 MTR TUBE", category: "Adhesives & Tapes", unit: "Roll" },
  { name: "CELLO TAPE WHITE – 3\", 60 MTR TUBE", category: "Adhesives & Tapes", unit: "Roll" },
  { name: "PACKING THREAD – PLASTIC", category: "Adhesives & Tapes", unit: "Roll" },
  { name: "FOAM TAPE TWO-SIDE – 1\"", category: "Adhesives & Tapes", unit: "Roll" },
  { name: "FOAM TAPE TWO-SIDE – 2\"", category: "Adhesives & Tapes", unit: "Roll" },
  { name: "FILE LACE – GREEN", category: "Files & Folders", unit: "Bundle" },
  { name: "PAPER TAG – 6\" SMALL", category: "Clips, Pins & Tags", unit: "Bundle" },
  { name: "PAPER TAG – 8\" MEDIUM", category: "Clips, Pins & Tags", unit: "Bundle" },
  { name: "PAPER TAG – 10\" LONG", category: "Clips, Pins & Tags", unit: "Bundle" },
  { name: "GUM CAN – 5 LITER CAN", category: "Adhesives & Tapes", unit: "Can" },
  { name: "PLASTIC CLIPS PREMIER No.2", category: "Clips, Pins & Tags", unit: "Box" },
  { name: "PLASTIC CLIPS DOLY No.2", category: "Clips, Pins & Tags", unit: "Box" },
  { name: "BINDER CLIPS – 19 MM", category: "Clips, Pins & Tags", unit: "Box" },
  { name: "BINDER CLIPS – 25 MM", category: "Clips, Pins & Tags", unit: "Box" },
  { name: "BINDER CLIPS – 32 MM", category: "Clips, Pins & Tags", unit: "Box" },
  { name: "BINDER CLIPS – 44 MM", category: "Clips, Pins & Tags", unit: "Box" },
  { name: "SCRIBBLING PADS GUPT'S – 888 WHITE", category: "Pads & Notebooks", unit: "Nos" },
  { name: "SCRIBBLING PADS GUPT'S – 777 WHITE", category: "Pads & Notebooks", unit: "Nos" },
  { name: "SCRIBBLING PADS GUPT'S – 666 WHITE", category: "Pads & Notebooks", unit: "Nos" },
  { name: "SCRIBBLING PADS GUPT'S – 555 WHITE", category: "Pads & Notebooks", unit: "Nos" },
  { name: "SCRIBBLING PADS GUPT'S – 888 RULE", category: "Pads & Notebooks", unit: "Nos" },
  { name: "SCRIBBLING PADS GUPT'S – 777 RULE", category: "Pads & Notebooks", unit: "Nos" },
  { name: "SCRIBBLING PADS GUPT'S – 666 RULE", category: "Pads & Notebooks", unit: "Nos" },
  { name: "SCRIBBLING PADS GUPT'S – 555 RULE", category: "Pads & Notebooks", unit: "Nos" },
  { name: "SPIRAL GUPT'S – 888 RULE", category: "Pads & Notebooks", unit: "Nos" },
  { name: "SPIRAL GUPT'S – 777 RULE", category: "Pads & Notebooks", unit: "Nos" },
  { name: "SPIRAL GUPT'S – 666 RULE", category: "Pads & Notebooks", unit: "Nos" },
  { name: "SPIRAL GUPT'S – 555 RULE", category: "Pads & Notebooks", unit: "Nos" },
  { name: "MARK LABELS (ROUND STICKERS) – CODE P-112, WHITE, DIA 4100", category: "General & Miscellaneous", unit: "Packet" },
  { name: "BELL CLIPS JEM CLIPS – 26 MM", category: "Clips, Pins & Tags", unit: "Box" },
  { name: "BELL PINS – 70 GRAMS", category: "Clips, Pins & Tags", unit: "Box" },
  { name: "STICK NOTE PAD – 3 IN 1 (PLASTIC)", category: "Pads & Notebooks", unit: "Nos" },
  { name: "STICK NOTE PAD – 4 IN 1", category: "Pads & Notebooks", unit: "Nos" },
  { name: "STICK NOTE PAD – 5 IN 1", category: "Pads & Notebooks", unit: "Nos" },
  { name: "GRAPH BOOKS – GENERAL – 100 PAGES", category: "Pads & Notebooks", unit: "Nos" },
  { name: "SEMI GRAPH BOOKS – 100 PAGES", category: "Pads & Notebooks", unit: "Nos" },
  { name: "SCHOLAR DRAWING BOARD PINS (1 Box = 10 Nos)", category: "Clips, Pins & Tags", unit: "Box" },
  { name: "SPONGE PADS – WATER DAMPER", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "LOOSE SPONGE – DAMPER", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "LONG NOTE BOOK – 220 PAGES WHITE", category: "Pads & Notebooks", unit: "Nos" },
  { name: "LONG NOTE BOOK – 220 PAGES RULE", category: "Pads & Notebooks", unit: "Nos" },
  { name: "TORTOISE WHITE THREAD ROLLS – CONE, ART No. 2320, G TKT 40S", category: "Adhesives & Tapes", unit: "Roll" },
  { name: "RUBBER BANDS – 1/2 KG PACKETS, BIG", category: "General & Miscellaneous", unit: "Packet" },
  { name: "RUBBER BANDS – 1/2 KG PACKETS, SMALL SIZE CASH", category: "General & Miscellaneous", unit: "Packet" },
  { name: "CARBON PAPERS – BLUE", category: "Pads & Notebooks", unit: "Box" },
  { name: "CARBON PAPERS – BLACK", category: "Pads & Notebooks", unit: "Box" },
  { name: "STICK FILES – LEGAL", category: "Files & Folders", unit: "Nos" },
  { name: "STICK FILES – A4 COLOUR", category: "Files & Folders", unit: "Nos" },
  { name: "STICK FILES – A4 TRANSPARENT", category: "Files & Folders", unit: "Nos" },
  { name: "KNIFE – GOOD QUALITY", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "ID CARD HOOKS", category: "General & Miscellaneous", unit: "Nos" },
  { name: "GIFT COVER", category: "General & Miscellaneous", unit: "Nos" },
  { name: "BOMBAY HANGING HOOKS – PLASTIC", category: "General & Miscellaneous", unit: "Nos" },
  { name: "CANON 2000 (G20) – MADE IN JAPAN, INK BOTTLES: 790C, 790BK, 790M, 790Y, PIXMA (NEC OFFICE)", category: "Inks & Printer Cartridges", unit: "Set" },
  { name: "BOUND NOTE BOOKS No.3 – 265 PAGES", category: "Pads & Notebooks", unit: "Nos" },
  { name: "BOUND NOTE BOOKS No.2 – 170 PAGES", category: "Pads & Notebooks", unit: "Nos" },
  { name: "TOTEM BALL PEN – MEOW", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "PEN ERASER", category: "Pencils & Sharpeners", unit: "Nos" },
  { name: "EPSON L3216 – INK BOTTLES: 003Y, 003M, 003C, 003BK", category: "Inks & Printer Cartridges", unit: "Set" },
  { name: "DAILY SHEET RULE – 34 LINES", category: "Pads & Notebooks", unit: "Ream" },
  { name: "COAD: 19-21, SIZE 48 CM X 56 CM – GARBAGE BAGS (MEDIUM) DUSTBIN COVERS", category: "General & Miscellaneous", unit: "Packet" },
  { name: "A4 WHITE PAPER HAMMERMILL – 75 GSM (COPIER)", category: "Papers & Copier Sheets", unit: "Ream" },
  { name: "LEGAL-FS WHITE PAPER HAMMERMILL – 75 GSM (COPIER)", category: "Papers & Copier Sheets", unit: "Ream" },
  { name: "A3 WHITE PAPER HAMMERMILL – 75 GSM (COPIER)", category: "Papers & Copier Sheets", unit: "Ream" },
  { name: "A4 COLOR SPRINT COPIER PAPER – 75 GSM YELLOW", category: "Papers & Copier Sheets", unit: "Ream" },
  { name: "A4 COLOR SPRINT COPIER PAPER – 75 GSM PINK", category: "Papers & Copier Sheets", unit: "Ream" },
  { name: "A4 COLOR SPRINT COPIER PAPER – 75 GSM GOLD SPOT", category: "Papers & Copier Sheets", unit: "Ream" },
  { name: "A4 COLOR SPRINT COPIER PAPER – 75 GSM LITE BLUE", category: "Papers & Copier Sheets", unit: "Ream" },
  { name: "A4 COLOR SPRINT COPIER PAPER – 75 GSM LIGHT GREEN (MINT)", category: "Papers & Copier Sheets", unit: "Ream" },
  { name: "8.6 WHITE PAPER – 1/4 TYPE (32 PACKETS = 1 BAG)", category: "Papers & Copier Sheets", unit: "Bag" }
];
