export interface StationaryCatalogItem {
  name: string;
  category: string;
  unit: string;
}

export const STATIONARY_CATALOG: StationaryCatalogItem[] = [
  { name: "APSARA PLATINUM PENCILS (1 box 10No's)", category: "Pencils & Sharpeners", unit: "Box" },
  { name: "CAMEL PENCIL WITH ERASER", category: "Pencils & Sharpeners", unit: "Nos" },
  { name: "APSARA NON DUST ERASER", category: "Pencils & Sharpeners", unit: "Nos" },
  { name: "NATRAJ SHARPNER", category: "Pencils & Sharpeners", unit: "Nos" },
  { name: "NATRAJ ERASER", category: "Pencils & Sharpeners", unit: "Nos" },
  { name: "SAINO STAR FLOW BALL PENS", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "SAINO SOFT TEC TRIO BALL PENS BLUE", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "SPEED BLUE PENS", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "SPEED BLACK PENS", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "SPEED RED PENS", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "NATARAJ PENS JOR", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "ADD GEL PENS GREEN", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "ADD GEL REFILLS GREEN GR-20", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "ADD GEL PENS BLUE", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "ADD GEL PENS BLACK", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "ADD GEL PENS RED", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "ADD GEL PIN - GEL GREEN", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "ADD GEL PIN - GEL RED", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "LINC OCEAN GEL PENS BLUE (1Packet = 3 Nos)", category: "Pens & Gel Pens", unit: "Packet" },
  { name: "LINC OCEAN GEL PENS BLACK (1Packet = 3 Nos)", category: "Pens & Gel Pens", unit: "Packet" },
  { name: "LINC OCEAN GEL PENS RED (1Packet = 3 Nos)", category: "Pens & Gel Pens", unit: "Packet" },
  { name: "LINC OCEAN GEL PENS GREEN (1Packet = 3 Nos)", category: "Pens & Gel Pens", unit: "Packet" },
  { name: "UNI BALL PENS GREEN", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "UNI BALL PENS BLACK", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "CAMEL OHP CD MARKER BLUE (1 BOX = 10 NO'S)", category: "Markers & Highlighters", unit: "Box" },
  { name: "CAMEL OHP CD MARKER BLACK (1 BOX = 10 NO'S)", category: "Markers & Highlighters", unit: "Box" },
  { name: "CAMEL OHP CD MARKER RED (1 BOX = 10 NO'S)", category: "Markers & Highlighters", unit: "Box" },
  { name: "CAMEL OHP CD MARKER GREEN (1 BOX = 10 NO'S)", category: "Markers & Highlighters", unit: "Box" },
  { name: "CAMEL PERMANENT MARKER RED", category: "Markers & Highlighters", unit: "Nos" },
  { name: "CAMEL PERMANENT MARKER BLUE", category: "Markers & Highlighters", unit: "Nos" },
  { name: "CAMEL PERMANENT MARKER BLACK", category: "Markers & Highlighters", unit: "Nos" },
  { name: "CAMEL WHITE BOARD MARKER PENS BLUE", category: "Markers & Highlighters", unit: "Nos" },
  { name: "CAMEL WHITE BOARD MARKER PENS BLACK", category: "Markers & Highlighters", unit: "Nos" },
  { name: "CAMEL WHITE BOARD MARKER PENS RED", category: "Markers & Highlighters", unit: "Nos" },
  { name: "CAMEL WHITE BOARD MARKER INK BLUE", category: "Inks & Stamp Pads", unit: "Bottle" },
  { name: "CAMEL WHITE BOARD MARKER INK BLACK", category: "Inks & Stamp Pads", unit: "Bottle" },
  { name: "CAMEL WHITE BOARD MARKER INK RED", category: "Inks & Stamp Pads", unit: "Bottle" },
  { name: "FABER CASTEL HIGHLIGHTER - YELLOW", category: "Markers & Highlighters", unit: "Nos" },
  { name: "CAMEL ERAZEX PENS - WHITE FLUID", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "SD MINI CUTTER STEEL BLADES", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "SKETCH PENS BLUE", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "SKETCH PENS BLACK", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "SKETCH PENS RED", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "SKETCH PENS GREEN", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "SKETCH PENS PINK", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "SKETCH PENS ALL CLOURS", category: "Pens & Gel Pens", unit: "Set" },
  { name: "KORES WHITE CHALKPIECES - DUST LESS (1 Box = 18 No's)", category: "Chalks & Media", unit: "Box" },
  { name: "KORES COLOUR CHALKPIECES - DUST LESS (1 Box = 18 No's)", category: "Chalks & Media", unit: "Box" },
  { name: "SONY CD", category: "Chalks & Media", unit: "Nos" },
  { name: "SONY DVD", category: "Chalks & Media", unit: "Nos" },
  { name: "CD MAILER (HANDLE WITH CARE)", category: "Chalks & Media", unit: "Nos" },
  { name: "CD COVERS", category: "Chalks & Media", unit: "Nos" },
  { name: "CD POUCHS (BAG)", category: "Chalks & Media", unit: "Nos" },
  { name: "ASHOK SEALING WAX (1 BOXE = 10 NO'S)", category: "General & Miscellaneous", unit: "Box" },
  { name: "NAYAGARA BOX FILES BIG", category: "Files & Folders", unit: "Nos" },
  { name: "NAYAGARA BOX FILES BIG STEEL CLIPS (GOOD GUALITY)", category: "Files & Folders", unit: "Nos" },
  { name: "NAYAGARA BOX FILES SMALL 1/4", category: "Files & Folders", unit: "Nos" },
  { name: "NAYAGARA URGENT & ORDINARY PADS (1 PACKET = 12 NO'S)", category: "Pads & Notebooks", unit: "Packet" },
  { name: "NAYAGARA PVC FOLDERS (LEGAL)", category: "Files & Folders", unit: "Nos" },
  { name: "NAYAGARA PVC FOLDERS - A4", category: "Files & Folders", unit: "Nos" },
  { name: "NAYAGARA PVC FOLDERS - A3", category: "Files & Folders", unit: "Nos" },
  { name: "SUN 150 FOLDERS - LEGAL", category: "Files & Folders", unit: "Nos" },
  { name: "SUN 150 FOLDERS - LEGAL (WITH OUT FILING)", category: "Files & Folders", unit: "Nos" },
  { name: "SUN 150 FOLDERS - A4", category: "Files & Folders", unit: "Nos" },
  { name: "SUN 200 FOLDERS - A4", category: "Files & Folders", unit: "Nos" },
  { name: "TAPE DISPENCER - TAPE CUTTER", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "ENVELOPS COVERS BROWN 6 X 4", category: "Envelopes & Covers", unit: "Nos" },
  { name: "ENVELOPS COVERS BROWN 10 X 4", category: "Envelopes & Covers", unit: "Nos" },
  { name: "ENVELOPS COVERS BROWN 11 X 5", category: "Envelopes & Covers", unit: "Nos" },
  { name: "COVERS BROWN - A4", category: "Envelopes & Covers", unit: "Nos" },
  { name: "ENVELOP COVERS WHITE 6 X 4", category: "Envelopes & Covers", unit: "Nos" },
  { name: "ENVELOP COVERS WHITE 10 X 4", category: "Envelopes & Covers", unit: "Nos" },
  { name: "ENVELOP COVERS WHITE 11 X 5", category: "Envelopes & Covers", unit: "Nos" },
  { name: "ENVELOP COVERS BROWN 11 X 5", category: "Envelopes & Covers", unit: "Nos" },
  { name: "CLOTH COVERS 11 X 5", category: "Envelopes & Covers", unit: "Nos" },
  { name: "CLOTH COVERS 12 X 10 (1 PACKET = 100 NO'S)", category: "Envelopes & Covers", unit: "Packet" },
  { name: "CLOTH COVERS 15 X 11 (1 PACKET = 100 NO'S)", category: "Envelopes & Covers", unit: "Packet" },
  { name: "CLOTH COVERS 16 X 12 (1 PACKET = 100 NO'S)", category: "Envelopes & Covers", unit: "Packet" },
  { name: "CLOTH COVERS A4 (1 PACKET = 100 NO'S)", category: "Envelopes & Covers", unit: "Packet" },
  { name: "KANGARO STAPLER -MISSION NO :10 ICON (1 BOX = 10 NO'S)", category: "Staplers & Punches", unit: "Box" },
  { name: "KANGARO STAPLER -MISSION 10-D (1 BOX = 10 NO'S)", category: "Staplers & Punches", unit: "Box" },
  { name: "KANGARO STAPLER - MISSION HP - 45 (BIG )", category: "Staplers & Punches", unit: "Nos" },
  { name: "KANGARO STAPLES PIN NO : 10 - 1M ( 1 BOX = 20 Packets)", category: "Staplers & Punches", unit: "Box" },
  { name: "KANGARO STAPLES PIN BIG 24/6", category: "Staplers & Punches", unit: "Box" },
  { name: "KANGARO PUNCHING MISSION SMALL 280- 8CM", category: "Staplers & Punches", unit: "Nos" },
  { name: "KANGARO PUNCHING MISSION DP - 500", category: "Staplers & Punches", unit: "Nos" },
  { name: "KANGARO PUNCHING MISSION DP - 700", category: "Staplers & Punches", unit: "Nos" },
  { name: "KANGARO SINGLE PUNCH 2mm Punching Capacity", category: "Staplers & Punches", unit: "Nos" },
  { name: "PAPER WEIGHT RUBBER GENERAL", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "NATRAJ SCALE LONG 30-CMS (GENARAL)", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "STEEL SCALES LONG", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "IRON CLIPS TIGER", category: "Clips, Pins & Tags", unit: "Nos" },
  { name: "KENT LAMINATION POUCH 75 X 105MM,250 MIC", category: "General & Miscellaneous", unit: "Packet" },
  { name: "FEVI STICK 8 GRMS (1 BOX = 30 NO'S)", category: "Adhesives & Tapes", unit: "Box" },
  { name: "FEVI KWIK 1 GRM", category: "Adhesives & Tapes", unit: "Nos" },
  { name: "CALCULATOR - CITIZEN - 512 GENERAL", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "CALCULATOR - CITICAL CT - 512 GST", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "CAMEL STAMP PAD MEDIUM - NO-2 ( 110 X 70MM) VIOLET ( 1 BOX = 10 NO'S)", category: "Inks & Stamp Pads", unit: "Box" },
  { name: "CAMEL STAMP PAD MEDIUM - (45) VIOLET", category: "Inks & Stamp Pads", unit: "Nos" },
  { name: "CAMEL STAMP PAD MEDIUM - NO-2 ( 110 X 70MM) GREEN ( 1 BOX = 10 NO'S)", category: "Inks & Stamp Pads", unit: "Box" },
  { name: "CAMEL STAMP PAD LARGE - (70) RED", category: "Inks & Stamp Pads", unit: "Nos" },
  { name: "CAMEL STAMP PAD LARGE - (70) VIOLET", category: "Inks & Stamp Pads", unit: "Nos" },
  { name: "CAMEL STAMP PAD LARGE UN (PLAIN ) - (70)", category: "Inks & Stamp Pads", unit: "Nos" },
  { name: "A4 TRANSPARENCY FILM (OHP SHEETS)", category: "Chalks & Media", unit: "Packet" },
  { name: "A4 COLOUR (OHP SHEETS)", category: "Chalks & Media", unit: "Packet" },
  { name: "BRILL STAMP PAD INK 700 ML -VIOLET", category: "Inks & Stamp Pads", unit: "Bottle" },
  { name: "BRILL STAMP PAD INK 350 ML - VIOLET", category: "Inks & Stamp Pads", unit: "Bottle" },
  { name: "BRILL STAMP PAD INK 350 ML - RED", category: "Inks & Stamp Pads", unit: "Bottle" },
  { name: "BRILL STAMP PAD INK 100 ML - GREEN", category: "Inks & Stamp Pads", unit: "Bottle" },
  { name: "NAPTHINE BALLS 500 G PACKET", category: "General & Miscellaneous", unit: "Packet" },
  { name: "PENCIL CELLS 9VOLTS", category: "General & Miscellaneous", unit: "Nos" },
  { name: "DURACELL AA (GENERAL SIZE) (1Sheets = 10 No's)", category: "General & Miscellaneous", unit: "Sheet" },
  { name: "DURACELL AAA ( SMALL SIZE) (1Sheets = 10 No's)", category: "General & Miscellaneous", unit: "Sheet" },
  { name: "NIPPO PENCIL CELLS AA -General SIZE", category: "General & Miscellaneous", unit: "Nos" },
  { name: "NIPPO PENCIL CELLS AAA- SMALL SIZE", category: "General & Miscellaneous", unit: "Nos" },
  { name: "LOCK - 50MM (Rs.50/-)", category: "General & Miscellaneous", unit: "Nos" },
  { name: "SCISSORE SMALL WILSON - 11.55 MM (ORDINARY)", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "SCISSORE MEDIUM EAGLE -666 - 16.5MM (ORDINARY)", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "SCISSORE BIG EAGLE -777 - 17.5MM (ORDINARY)", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "DUSTER AGRA", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "WHITE BOARD DUSTER", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "PRIMIER CELLO TAP 1\"", category: "Adhesives & Tapes", unit: "Roll" },
  { name: "CELLO TAPE BROWN 1. 1/2 \" 60MTR TUBE", category: "Adhesives & Tapes", unit: "Roll" },
  { name: "CELLO TAPE BROWN 2\" 60MTR TUBE", category: "Adhesives & Tapes", unit: "Roll" },
  { name: "CELLO TAPE BROWN 3\" 60MTR TUBE", category: "Adhesives & Tapes", unit: "Roll" },
  { name: "CELLO TAPE WHITE 1\" 60MTR TUBE", category: "Adhesives & Tapes", unit: "Roll" },
  { name: "CELLO TAPE WHITE 1. 1/2\" 60MTR TUBE", category: "Adhesives & Tapes", unit: "Roll" },
  { name: "CELLO TAPE WHITE 2\" 60MTR TUBE", category: "Adhesives & Tapes", unit: "Roll" },
  { name: "CELLO TAPE WHITE 3\" 60MTR TUBE", category: "Adhesives & Tapes", unit: "Roll" },
  { name: "PACKING THREAD (PLASTIC)", category: "Adhesives & Tapes", unit: "Roll" },
  { name: "FOAM TAPE TWO SIDE 1''", category: "Adhesives & Tapes", unit: "Roll" },
  { name: "FOAM TAPE TWO SIDE 2''", category: "Adhesives & Tapes", unit: "Roll" },
  { name: "FILE LACE ( GREEN )", category: "Files & Folders", unit: "Bundle" },
  { name: "PAPER TAG 6\" SMALL", category: "Clips, Pins & Tags", unit: "Bundle" },
  { name: "PAPER TAG 8\" MEDIUM", category: "Clips, Pins & Tags", unit: "Bundle" },
  { name: "PAPER TAG 10\" LONG", category: "Clips, Pins & Tags", unit: "Bundle" },
  { name: "GUM CAN 5 LITER CAN", category: "Adhesives & Tapes", unit: "Can" },
  { name: "PLASTIC CLIPS PREMIER NO-2", category: "Clips, Pins & Tags", unit: "Box" },
  { name: "PLASTIC CLIPS DOLY NO-2", category: "Clips, Pins & Tags", unit: "Box" },
  { name: "BINDER CLIPS 19 MM", category: "Clips, Pins & Tags", unit: "Box" },
  { name: "BINDER CLIPS 25 MM", category: "Clips, Pins & Tags", unit: "Box" },
  { name: "BINDER CLIPS 32 MM", category: "Clips, Pins & Tags", unit: "Box" },
  { name: "BINDER CLIPS 44 MM", category: "Clips, Pins & Tags", unit: "Box" },
  { name: "SCRIBBLING PADS GUPTS' S - 888 WHITE", category: "Pads & Notebooks", unit: "Nos" },
  { name: "SCRIBBLING PADS GUPTS' S - 777 WHITE", category: "Pads & Notebooks", unit: "Nos" },
  { name: "SCRIBBLING PADS GUPTS' S - 666 WHITE", category: "Pads & Notebooks", unit: "Nos" },
  { name: "SCRIBBLING PADS GUPTS' S - 555 WHITE", category: "Pads & Notebooks", unit: "Nos" },
  { name: "SCRIBBLING PADS GUPTS' S - 888 RULE", category: "Pads & Notebooks", unit: "Nos" },
  { name: "SCRIBBLING PADS GUPTS' S - 777 RULE", category: "Pads & Notebooks", unit: "Nos" },
  { name: "SCRIBBLING PADS GUPTS' S - 666 RULE", category: "Pads & Notebooks", unit: "Nos" },
  { name: "SCRIBBLING PADS GUPTS' S - 555 RULE", category: "Pads & Notebooks", unit: "Nos" },
  { name: "SPIRAL GUPT'S - 888 RULE", category: "Pads & Notebooks", unit: "Nos" },
  { name: "SPIRAL GUPT'S - 777 RULE", category: "Pads & Notebooks", unit: "Nos" },
  { name: "SPIRAL GUPT'S - 666 RULE", category: "Pads & Notebooks", unit: "Nos" },
  { name: "SPIRAL GUPT'S - 555 RULE", category: "Pads & Notebooks", unit: "Nos" },
  { name: "MARK LABELS (ROUND STICKERS) CODE -P-112,WHITE ,SIZE-DIA4100", category: "General & Miscellaneous", unit: "Packet" },
  { name: "BELL CLIPS JEM CLIPS 26MM", category: "Clips, Pins & Tags", unit: "Box" },
  { name: "BELL PINS 70 GRAMS", category: "Clips, Pins & Tags", unit: "Box" },
  { name: "STICK NOTE PAD 3 IN 1 (PLASTIC)", category: "Pads & Notebooks", unit: "Nos" },
  { name: "STICK NOTE PAD 4 IN 1", category: "Pads & Notebooks", unit: "Nos" },
  { name: "STICK NOTE PAD 5 IN 1", category: "Pads & Notebooks", unit: "Nos" },
  { name: "GRAPH BOOKS GENERAL 100 PAGES", category: "Pads & Notebooks", unit: "Nos" },
  { name: "SEMI GRAPH BOOKS 100 PAGES", category: "Pads & Notebooks", unit: "Nos" },
  { name: "SCHOLAR DRAWING BOARD PINS ( 1 Boxe = 10 No's)", category: "Clips, Pins & Tags", unit: "Box" },
  { name: "SPONZE PADS (WATER DAMPER)", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "LOOSE SPONG ( DAMPER )", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "LONG NOTE BOOK 220 PAGES WHITE", category: "Pads & Notebooks", unit: "Nos" },
  { name: "LONG NOTE BOOK 220 PAGES RULE", category: "Pads & Notebooks", unit: "Nos" },
  { name: "TORTOISE WHITE THREAD ROLLS (CONE ) ART NO 2320,G TKT 40S", category: "Adhesives & Tapes", unit: "Roll" },
  { name: "RUBEBER BANDAS 1/2 Kg Packets BIG", category: "General & Miscellaneous", unit: "Packet" },
  { name: "RUBBER BANDAS 1/2 Kg Packets SMALL SIZE CASH", category: "General & Miscellaneous", unit: "Packet" },
  { name: "CARBON PAPERS - BLUE", category: "Pads & Notebooks", unit: "Box" },
  { name: "CARBON PAPERS - BLACK", category: "Pads & Notebooks", unit: "Box" },
  { name: "STICK FILES - LEGAL", category: "Files & Folders", unit: "Nos" },
  { name: "STICK FILES - A4 COLOUR", category: "Files & Folders", unit: "Nos" },
  { name: "STICK FILES - A4 (TRANSPARENT)", category: "Files & Folders", unit: "Nos" },
  { name: "KNIFE (GOOD QUALITY)", category: "Desk Tools & Scales", unit: "Nos" },
  { name: "ID CARD HOOKS", category: "General & Miscellaneous", unit: "Nos" },
  { name: "GIFT COVER", category: "General & Miscellaneous", unit: "Nos" },
  { name: "BOMBAY HANGING HOOKS PLASTIC", category: "General & Miscellaneous", unit: "Nos" },
  { name: "Canon 2000 (G20) Made in Japan, Ink Bottles :- 790C, 790BK,790M, 790Y,Pixma (NEC OFFICE)", category: "Inks & Printer Cartridges", unit: "Set" },
  { name: "BOUND NOTE BOOKS NO-3 (PAGES 265)", category: "Pads & Notebooks", unit: "Nos" },
  { name: "BOUND NOTE BOOKS NO-2 (PAGES 170)", category: "Pads & Notebooks", unit: "Nos" },
  { name: "TOTEM BALL PEN MEOW", category: "Pens & Gel Pens", unit: "Nos" },
  { name: "PEN ERASER", category: "Pencils & Sharpeners", unit: "Nos" },
  { name: "Epson (L3216) - Ink Bottles 003Y, 003M, 003C, 003BK", category: "Inks & Printer Cartridges", unit: "Set" },
  { name: "Daily sheet Rule 34 lines", category: "Pads & Notebooks", unit: "Ream" },
  { name: "COAD :19-21, SIZE 48CM *56 CM GARBAGE BAGS (MEDIUM) DUST BI COVERS", category: "General & Miscellaneous", unit: "Packet" }
];
